import type { ProviderId } from "./types";

// Keys are built from ids generated by newId(): anything else could escape the prefix (for example "../").
const MEETING_ID =
	/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const EXTENSION = /^[a-z0-9]{1,8}$/;

function assertMeetingId(meetingId: string): void {
	if (!MEETING_ID.test(meetingId)) {
		throw new Error(`Invalid meeting id: ${meetingId}`);
	}
}

export function audioKey(meetingId: string, extension: string): string {
	assertMeetingId(meetingId);
	const normalized = extension.replace(/^\./, "").toLowerCase();
	if (!EXTENSION.test(normalized)) {
		throw new Error(`Invalid audio extension: ${extension}`);
	}
	return `audio/${meetingId}.${normalized}`;
}

export function rawKey(meetingId: string, provider: ProviderId): string {
	assertMeetingId(meetingId);
	return `raw/${meetingId}/${provider}.json`;
}

export function extractionKey(meetingId: string): string {
	assertMeetingId(meetingId);
	return `extraction/${meetingId}.json`;
}

export async function putJson(
	bucket: R2Bucket,
	key: string,
	value: unknown,
): Promise<void> {
	await bucket.put(key, JSON.stringify(value), {
		httpMetadata: { contentType: "application/json" },
	});
}

// Returns null when the key does not exist. The caller validates the shape of the value.
export async function getJson(bucket: R2Bucket, key: string): Promise<unknown> {
	const object = await bucket.get(key);
	if (object === null) {
		return null;
	}
	try {
		return await object.json();
	} catch (error) {
		throw new Error(`Invalid JSON in R2 object ${key}`, { cause: error });
	}
}
